# Generated by Django 4.2.3 on 2023-08-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherID', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('room', models.IntegerField()),
            ],
        ),
    ]
