# Generated by Django 4.2.3 on 2023-08-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('pointsPossible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('gradeLevel', models.IntegerField()),
                ('courses', models.ManyToManyField(to='student_management_system.course')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('students', models.ManyToManyField(to='student_management_system.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pointsEarned', models.IntegerField()),
                ('assignment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_system.assignment')),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_system.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_system.teacher'),
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('interventions', models.TextField()),
                ('student', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_system.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_management_system.course'),
        ),
    ]
