# Generated by Django 4.2.3 on 2023-08-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentID', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField()),
                ('pointsPossible', models.IntegerField()),
                ('pointsEarned', models.IntegerField()),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviorID', models.IntegerField()),
                ('description', models.CharField()),
                ('interventions', models.CharField()),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField()),
                ('teacherID', models.IntegerField()),
                ('assignmentID', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentID', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('studentID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('gradeLevel', models.IntegerField()),
                ('parentID', models.IntegerField()),
                ('courseID', models.IntegerField()),
            ],
        ),
    ]
