# Generated by Django 4.2.3 on 2023-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0002_assignment_behavior_course_parent_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentID', models.IntegerField()),
                ('studentID', models.IntegerField()),
                ('courseID', models.IntegerField()),
                ('pointsEarned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('courseID', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='pointsEarned',
            new_name='courseID',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='studentID',
        ),
        migrations.RemoveField(
            model_name='course',
            name='assignmentID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courseID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parentID',
        ),
    ]
