# Generated by Django 4.2.3 on 2023-08-09 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_alter_assignment_id_alter_behavior_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dueDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
