# Generated by Django 4.2.3 on 2023-08-09 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_assignment_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
